### ISSUE TITLE
[FEATURE] Discord charts support

### ISSUE THREAD

**Issue by htotoo** [w1ld3r/crypto-signal#7]
Hello, 
It would be great to have the Notifications to Discord include the charts generated too.
Based on this doc: https://discord.com/developers/docs/resources/webhook#execute-webhook  it is possible.

Thanks for thinking about it.

**Comment by w1ld3r** [comment]
Hello @htotoo,
I understand that some people are interesting in this functionality (send charts in notification) but, I really don't like this because it's not clear enouth and I prefere to look at my charts on Coinigy.
So to be honest with you, I will not take time to implement this.
Hope you understand.

**Comment by htotoo** [comment]
No problem, you inspired me to do it myself. But yet it is a so ugly implementation; if i'll clean it i'll post a PR. In short: changed webcord lib to discord_webhook lib, and used it's add_file method.

**Comment by w1ld3r** [comment]
Yes I know but we have do deal with it ... I have no time to re-implement everything in a python state of art.

**Comment by w1ld3r** [comment]
Thanks again @incontestableness
